# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FaissNeuralSearch": "00_neural_search.ipynb",
         "PDF_DIR_PATH": "01_qa_on_pdf.ipynb"}

modules = ["neural_search.py",
           "pdf_qa.py"]

doc_url = "https://mallahyari.github.io/mlnotes/"

git_url = "https://github.com/mallahyari/mlnotes/tree/master/"

def custom_doc_links(name): return None
