# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["neural_search.py"]

doc_url = "https://mallahyari.github.io/mlnotes/"

git_url = "https://github.com/mallahyari/mlnotes/tree/master/"

def custom_doc_links(name): return None
